### ISSUE TITLE
Yoast SEO + Mesh content text

### ISSUE THREAD

**Issue by strarsis** [linchpin/mesh#118]
The Yoast SEO plugin doesn't seem to find any text in Mesh content:

> Bad SEO score The text contains 0 words. This is far below the recommended minimum of 300 words. Add more content that is relevant for the topic.

**Comment by aaronware** [comment]
I've had this in the works for a while. I needed to create a basic framework for integrations. It's pretty much ready for a peer review in the coming days

**Comment by aaronware** [comment]
Fixed and merged into develop for 1.2
