### ISSUE TITLE
Background image update automatically updates and publishes section

### ISSUE THREAD

**Issue by jarbro** [linchpin/mesh#128]
1. In a mesh section on a published page that has a background image.
2. Replace background image with another image.
3. Image is automatically updated on the live site w/o ever hitting the update button on mesh section or WP Update button.

WP Version: 4.7.5
Mesh Version 1.1.6

**Comment by aaronware** [comment]
@maxinacube sending this one your way. @nate-allen and I were able to confirm and replicate
