### ISSUE TITLE
Reordering sections breaks in 4.8

### ISSUE THREAD

**Issue by aaronware** [linchpin/mesh#135]
This was reported on .org https://wordpress.org/support/topic/issues-i-have-discovered/

Click reorder sections and drag one section to another position and save the order. You have to refresh the page otherwise the dragged section isn’t rich text editable or editable at all.

I think the overlay isn't being toggled off.

**Comment by aaronware** [comment]
After some debugging it only seemed to occur on the section that you actively re-order. All other sections appeared to be able to be ordered accordingly.

**Comment by maxinacube** [comment]
@aaronware I'm still seeing this issue.

If I go through the process of adding sections, reordering, and then saving the sections, any section that has been collapsed **and** reordered is not editable with the visual editor.

There are some other bugs going on as well with some sections collapsing for reorder, while some don't. Trying to find a pattern of why some collapse, it seems like - starting from the bottom section - every other section is collapsed, with the last section being collapsed.

Also, I have a large space at the top of the sections appear when reorder has been triggered - this space persists until the page has been refreshed manually or with a draft, save, or update. The space being created is the welcome box (https://cldup.com/4lj_t70-qO.png), it has an opacity of 0 but gets a display: block property when reorder is triggered.

**Comment by aaronware** [comment]
Nooooooooooooooooo!

**Comment by aaronware** [comment]
Dumb question. Did you happen to regenerate the JS?

**Comment by maxinacube** [comment]
Yeah, I double checked that the JS the page is loading matched the changes from the bug/135 branch.

**Comment by aaronware** [comment]
Lame ok.

**Comment by aaronware** [comment]
@maxinacube take a look when you get a chance. I think I fixed up the issue you showed me
