### ISSUE TITLE
after update: undefined variable: push_pull

### ISSUE THREAD

**Issue by ErkkiTuomiLMSaatchi** [linchpin/mesh#167]
Hi,

After updating the plugin I got this notice after all mesh-sections that is visible on the site:

```
Notice
: Undefined variable: push_pull in
/home/tykssaatio/public_html/wordpress/wp-content/plugins/mesh/templates/mesh-columns-2.php
on line
42
```
I wonder if anyone else have had this problem?

Anyway, I just removed that line from the array, and the layout works again just fine. But ofcourse, I'm not liking that updating the plugin might result this kind of sitewide problem.

greets,

Eki

**Comment by aaronware** [comment]
Thanks @ErkkiTuomiLMSaatchi for the feedback. Agree about having an undefined error in the code. Though I would suggest not displaying errors on the front end of your website. Having an undefined variable is just a `notice` and not a `fatal` error so it would typically not affect your display unless you are explicitly saying. 

`define( 'WP_DEBUG_DISPLAY', true );`

**Comment by strarsis** [comment]
+1 for getting rid of this notice. It also messes around with the layout (flex based custom css for the mesh container elements).

**Comment by aaronware** [comment]
Rolling out in 1.2.1

**Comment by ErkkiTuomiLMSaatchi** [comment]
Thanks! 
I'll get rid of that notice. Thanks fot the tip, I didn't know that I could disable the notice.
Great that it get's fixed.

**Comment by aaronware** [comment]
@ErkkiTuomiLMSaatchi if you grab 1.2.1 in a plugin update those items should be fixed.
