### ISSUE TITLE
Caldera Forms plugin conflict: input elements missing

### ISSUE THREAD

**Issue by strarsis** [linchpin/mesh#169]
Related issue: https://github.com/CalderaWP/Caldera-Forms/issues/1883

The issue goes away when Mesh plugin is disabled.
This issue hadn't occured with older Mesh plugin releases.

The `<input>` elements (`text` / `radio` / `tel` type) are missing, only the labels are visible.
Only the `<textarea>` element markup is correctly outputted.

Output:
```html
<div class="">
					</div>
````

Expected:
```html
<div class="">
		<input required="" type="tel" data-field="fld_161046" class=" form-control" id="fld_161046_1" name="fld_161046" value="" data-type="tel" aria-required="true" aria-labelledby="fld_161046Label">			</div>
````

**Comment by aaronware** [comment]
Hey @strarsis, this is definitely due to sanitizing of elements. @maxinacube is pushing out a patch that will be merged in shortly

**Comment by aaronware** [comment]
Rolling out in 1.2.1
