### ISSUE TITLE
Warnings when mesh not enabled for any post types yet

### ISSUE THREAD

**Issue by strarsis** [linchpin/mesh#184]
By default Mesh is not enabled for any post types.
When opening the Mesh settings page (e.g. for enabling it for the page post type), 
I see several warning messages:
````
( ! ) Warning: array_keys() expects parameter 1 to be array, string given in /srv/www/web/app/plugins/mesh/class.mesh-templates.php on line 117
( ! ) Warning: array_merge(): Argument #2 is not an array in /srv/www/web/app/plugins/mesh/class.mesh-templates.php on line 118
````
The CSS list input is partially visible.
After selecting at least one post type for enabling Mesh for it, 
the warnings go away and the CSS list works correctly.

**Comment by aaronware** [comment]
This is updated and will be going out with 1.2.4

**Comment by aaronware** [comment]
Rolled out in 1.2.4
