### ISSUE TITLE
Firefox issues

### ISSUE THREAD

**Issue by Dontorpedo** [linchpin/mesh#187]
some JS issues:
TypeError: $sections is undefined admin-mesh-core.js:367:3

and:
ReferenceError: event is not defined

Mesh pagebuilder doesn't work in firefox..

in chrome they are visual issues while working with the grid.

**Comment by dannio** [comment]
That's not the only issue. Upon loading it fires the following error:

ReferenceError: event is not defined
admin-mesh-core.js:81:28

init
admin-mesh-core.js:81:28
<anonymous>
admin-mesh-core.js:1086:1
i
/wp-admin/load-scripts.php:2:27444
fireWith
/wp-admin/load-scripts.php:2:28213
ready
/wp-admin/load-scripts.php:2:30004
K
/wp-admin/load-scripts.php:2:30366

**Comment by aaronware** [comment]
I think you're good to go. Take a look after updating to 1.2.3
