### ISSUE TITLE
Row level CSS classes to support Foundation alignment classes

### ISSUE THREAD

**Issue by maxinacube** [linchpin/mesh#188]
There should be a default input field available to add custom CSS classes to a section's `.row`

Reference WordPress support thread: [Row level CSS classes to support Foundation alignment classes](https://wordpress.org/support/topic/row-level-css-classes-to-support-foundation-alignment-classes/)

**Comment by maxinacube** [comment]
Untagged commit for addition of row class field ----> 281d1f8

**Comment by aaronware** [comment]
Rolled out in 1.2.4
