### ISSUE TITLE
Make a constant to reference for saving/display controls

### ISSUE THREAD

**Issue by maxinacube** [linchpin/mesh#189]
There are currently 2 files holding information about the same control fields.

**class.mesh.php**
`save_post`
lines 464-476

**class.mesh-controls.php**
`mesh_section_controls` and `mesh_block_controls`
117-170 and 292-312

The descriptive arrays in class.mesh-controls.php should be a constant that is referenced in both files.

With reference update, the field type is also passed. The field type should be taken advantage of within class.mesh.php's `save_post` function to dynamically save default fields and also custom fields passed through the `mesh_section_controls` and `mesh_block_controls` filters.

**Comment by aaronware** [comment]
This was actually fixed up in 1.2.4 I just realized it when doing some issue pruning
