### ISSUE TITLE
Reorder section controls and improve control styles

### ISSUE THREAD

**Issue by maxinacube** [linchpin/mesh#204]
### Reorder section controls and improve control styles

Section controls should be split into a 9 column for text/checkbox controls and a 3 column for the featured image. The 9 column controls should be in the following order:

* Section ID
* Section Class
* Row Class
* Collapse Padding
* Push/Pull
* Equalize

After re-order, improve controls styles to limit height of controls panel when scrolled open and to improve spacing and appearance.

**Comment by aaronware** [comment]
Rolled out in 1.2.4
