### ISSUE TITLE
Center smaller width column not working

### ISSUE THREAD

**Issue by sitesandsuch** [linchpin/mesh#235]
Thanks again for this wonderful plugin. In version 1.2.5.2 setting the width of a single column to 8 (for example) and then checking the 'centered' option centres the column in the backend as expected. But not on the page itself. No additional css classes are introduced. This should add 'align-center' to the column container (eg 'row')?

**Comment by aaronware** [comment]
Oh shoot. Yep I caught that yesterday too. I have something I'll be pushing out shortly.

**Comment by aaronware** [comment]
Pushed out in 1.2.5.3
