### ISSUE TITLE
Can't set column title to nothing ('No Section Title') without content

### ISSUE THREAD

**Issue by strarsis** [linchpin/mesh#241]
When saving a Mesh section with the title of a Mesh column set to nothing 
(so that 'No Section title' is displayed), the title won't be updated (to nothing).

As workaround, for updating the column title to nothing, the section has to be updated with a content set to something (and can be emptied later when the title has been correclty updated).

**Comment by aaronware** [comment]
Gotcha, In this scenario are you merely trying to hit the title but keep the markup?

**Comment by aaronware** [comment]
This should be good now in 1.2.5.4
