### ISSUE TITLE
mesh_get_section_attributes adding quotes as &quote to ID

### ISSUE THREAD

**Issue by sitesandsuch** [linchpin/mesh#245]
Version 1.2.5.3:
The ID of the section is rendered as id=&quot;mesh-section-5&quot;.

This is caused by 
echo esc_html( $section_attributes );
in utilities.php - line 194

I have fixed it by removing the esc_html function. This is OK as sanitation already done in line 170 and 171?

**Comment by anitagraham** [comment]
Would like to see this fixed as it makes the section id useless. `id=""summary""` and
