### ISSUE TITLE
Section Title Bugged when deleted

### ISSUE THREAD

**Issue by mitchelsliwa** [linchpin/mesh#249]
If you add a section title, and then try and remove it causes a bug by leaving behind an empty h3 tag.  

On another site, it just wouldn't delete the text either. I had to replace with a "." instead of a word. Spaces weren't respected if I tried to just leave just a space instead of text, it would keep the previous entry and ignored the " " entry. 

https://screencast.com/t/Hax1A3QINk

**Comment by aaronware** [comment]
This _should_ be all set in 1.2.5.4
