### ISSUE TITLE
allow mesh column to have an id and/or more than one 1 class

### ISSUE THREAD

**Issue by anitagraham** [linchpin/mesh#251]
This would allow css targetting of a column by name/slug.
I am using a foundation class now (card) but need to target each column as well.

Particularly useful in light of the fact that the section id is not useable.

**Comment by aaronware** [comment]
You can add multiple classes in the css classes area of each column/block. They are space delimited similar to how a html attribute would be formatted `class="my-class my-otherclass"`. So you would do the same thing in the css classes field for both sections and blocks

**Comment by anitagraham** [comment]
That is, in fact, what I have done.
