### ISSUE TITLE
Latest release contains wp_die

### ISSUE THREAD

**Issue by strarsis** [linchpin/mesh#255]
In latest release of Mesh plugin (v1.2.5.4) is apparent debug code in 
`utilities.php`:587 (in `mesh_maybe_show_section_title` method) which results in impartial page rendered:
```php
wp_die( print_r( $section_title_matches, true ) );
````
This is not apparent in code in master of this repository, 
you have to download the Mesh plugin from WordPress plugin repository 
(same issue also with wpackagist).

**Comment by aaronware** [comment]
That's odd. I'll make another build immediately.

**Comment by aaronware** [comment]
I pushed out a fix to master and to .org
Good catch, sorry about that.
