### ISSUE TITLE
Number of Blocks does not update on change, only on save

### ISSUE THREAD

**Issue by fischfood** [linchpin/mesh#66]
When changing a Mesh section to have a different number of columns, the number of columns does not change until save, (this is why push/pull does not appear until you save to two columns).

**Comment by fischfood** [comment]
The columns do adjust to display the correct number, but the options in the top most "More" section do not update to show what should be there ( Push/Pull , Equalize )

**Comment by aaronware** [comment]
This is fixed within #72
