### ISSUE TITLE
Add an anchor/id within the more options in order to anchor to a section

### ISSUE THREAD

**Issue by aaronware** [linchpin/mesh#7]
This would be really useful for menus or anchor links.

**Comment by aaronware** [comment]
If you click Add Section. After the section is created and displayed. Jump the user to that section. Animate the scroll so the the user sees we are moving them to where they need be.

**Comment by prkirby** [comment]
Is there any progress to this? This would be perfect for single page/landing page solutions.

**Comment by aaronware** [comment]
I've tested this out and it looks good to go based on the work @maxinacube did a while back. Pushing this out with 1.2.4

**Comment by aaronware** [comment]
This was pushed out yesterday with 1.2.4
