### ISSUE TITLE
"content" is replaced with section ID when copying from a page or template

### ISSUE THREAD

**Issue by erroneous5000** [linchpin/mesh#70]
This happens when copying sections from a page and when copying from a template.

The text "content" is replaced with "mesh-section-editor-#" where # is the section ID

**Comment by aaronware** [comment]
@erroneous5000 was that on the front end or within the admin?

**Comment by erroneous5000** [comment]
In the admin initially but if saved/published obviously it effects the front-end.

The best most common example is in image links where it should say "/wp-content" it becomes "/wp-mesh-editor-section-#" and then when saved that becomes a broken image.

**Comment by aaronware** [comment]
This was fixed by @nate-allen in 1.1.7
