### ISSUE TITLE
Allow developers to filter section and column options

### ISSUE THREAD

**Issue by aaronware** [linchpin/mesh#72]
Create a method and filter to allow developers to add new options to both sections and blocks.

**Comment by aaronware** [comment]
Controls are now within a filterable object. This object should be extended further in order to be able to categorize items into "visible options" and "more options". Visible options are currently the "Column / Layout" dropdown as well as the "Show title" checkbox.

It would give developers more flexibility to be able to show fields in the 2 aforementioned areas.

**Comment by nate-allen** [comment]
@aaronware Take a look at [feature/72](/linchpin/mesh/tree/feature/72) branch when you get a chance. There's definitely more we could add to this to make it even more extendable, for example:

- `default`: Allow a default value in a field
- `before_field`, `after_field`: Allow markup before/after the field
- `attributes`: Allow any attributes (like`data-foo`, `required`, etc)
- `sanitization_cb`: A callback for sanitizing data before adding to the database

But not sure if any of these are critical for this release.

**Comment by aaronware** [comment]
These are all great suggestions. I feel like the sanitization CB is pretty important to have. But all the others ones are really nice to have as well.

**Comment by aaronware** [comment]
I can peer review a little later on this afternoon
