### ISSUE TITLE
Visual editor rendered HTML saved instead raw text

### ISSUE THREAD

**Issue by strarsis** [linchpin/mesh#73]
Publishing/updating a mesh column editor with a WordPress gallery shortcode added 
results in it being rendered as HTML and also being changed visually 
(visible in editor after reloading the editor page).

Edit: This happens when the Mesh row is updated 
with the gallery shown in "Visual" editor mode.
In "Text" editor mode with only the gallery shortcode shown, 
the gallery shortcode is correctly preserved when updating.

**Comment by strarsis** [comment]
I find this quite a higher priority issue because a normal user easily destroys the existing content and has to revise to the changes before saving it - one also easily forgets to switch to Text mode in editor before saving.

**Comment by aaronware** [comment]
I'll be taking a look at this over the weekend.

**Comment by strarsis** [comment]
@aaronware: Is there any quick fix possible?

**Comment by aaronware** [comment]
@strarsis I finally found some time this evening to take a look. I'll keep you posted. If I can't get a release buttoned up I can at least make a branch that you can pull from

**Comment by aaronware** [comment]
@strarsis not the *BEST* solution but I did notice that if you save while in text view it will save the shortcode version of the code and not the rendered html. I'm still looking into this further but wanted to keep you in the loop on my testing

**Comment by aaronware** [comment]
@strarsis I think this is good to go but it definitely needs some testing. In the meantime if you want to pull down branch issue/73 you will see adjustments to the javascript as well as the save_post methods within the php.

**Comment by strarsis** [comment]
@aaronware: I tested with WordPress native gallery and Caldera forms and in both cases it works, the shortcodes are preserved.

**Comment by aaronware** [comment]
@strarsis awesome, thanks for giving it a test. I have some testing planned for later today on some of our clients that also use Mesh pretty extensively that I want to confirm work if they look good I'll be doing a release in the next day or so. We have a few fixes we've put in place that can go out.
