### ISSUE TITLE
Configure repository to use a code review workflow

### ISSUE THREAD

**Issue by desrosj** [linchpin/mesh#78]
Currently, the repo is the wild wild west, and it is hard to tell how to contribute.

Let's get a flow going and add a `CONTRIBUTING.MD` file to help new contributors.

`master` should only contain production ready, released code. `develop` should contain the latest and greatest. All code contributions should be made through a pull request into `develop`. This will allow our automated processes to run for each contribution.

**Comment by aaronware** [comment]
@desrosj any update on this?

**Comment by desrosj** [comment]
I submitted a support request for this. For some reason, the pull request integration disappeared. I will follow up on this shortly.
