### ISSUE TITLE
Localization Edits

### ISSUE THREAD

**Issue by Shannonjmalloy** [linchpin/mesh#90]
A few strings below are missing the text domain and settings.php is missing a few translatable strings(also seen below). 
There's also a typo: 'Organzing' should be 'Organizing'.

section-controls.php line 41 // `<?php _e( 'More Options' ); ?>`

section-controls.php line 130 // `<?php _e( 'Browse revisions' ); ?>`

section-blocks.php line 130 // `<?php _e( 'Browse revisions' ); ?>`

admin/settings.php lines 90-92 // `<h2><?php esc_html_e( ' Linchpin is a Digital Agency that specializes in WordPress' ); ?></h2> <p>We loving giving back to the WordPress community through Plugins, Tools/Utilities and through Organzing <a href="http://meetup.com/WordPressRI/">WordPress Rhode Island</a> and WordCamp Rhode Island</p> <p>Check our our <a href="https://linchpin.agency" target="_blank">site</a>. or visit our various profiles below or come say hi at a local event.</p>`

**Comment by desrosj** [comment]
Thanks @Shannonjmalloy, all set in #91.
