### ISSUE TITLE
Grunt processes need adjustements

### ISSUE THREAD

**Issue by desrosj** [linchpin/mesh#95]
Currently, `grunt build` only minifies sass, and `grunt watch` or `grunt` does all of the heavy lifting of a build process.

It should be the other way around.

Ideally, `grunt watch` should compile sass, and uglify and concat JS. `grunt build` should perform those operations, then perform `addtextdomain`, and then `copy` to populate the build directory for release.

**Comment by aaronware** [comment]
This was already merged
